name: publish-to-npm
run-name: ${{ github.actor }} is publishing to npm
on:
  workflow_call:
    inputs:
      bump_level:
        description: type of version bump
        required: true
        type: string
      github_token:
        description: token used to pull and commit to github
        default: ${{ github.token }}
        required: false
        type: string
    secrets:
      NPM_CLASSIC_TOKEN:
        required: true

jobs:
  build-and-publish:
    name: build and publish package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ inputs.github_token || github.token }}
      - name: "set up git author identity"
        run:
          git config user.name "github-actions[bot]";
          git config user.email "github-actions[bot]@users.noreply.github.com";
      - uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: 'package-lock.json'
          node-version-file: '.nvmrc'
      - name: "install deps"
        run: npm ci
      - env:
          NPM_TOKEN: ${{ secrets.NPM_CLASSIC_TOKEN }}
        name: "export login token"
        run: "echo //registry.npmjs.org/:_authToken=$NPM_TOKEN > ./.npmrc"
      - env:
          VERSION: ${{ inputs.bump_level }}
        name: "bump version"
        run: "npm version $VERSION"
      - name: "publishing"
        run: "npm publish --access=public"
